// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


function make(bits, name) {
  return new File(bits, name);
}

var File$1 = /* module */[/* make */make];

function make$1() {
  return new FileReader();
}

var FileReader$1 = /* module */[/* make */make$1];

exports.File = File$1;
exports.FileReader = FileReader$1;
/* No side effect */
