// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var BsFileDemo$BsFile = require("./BsFileDemo.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, BsFileDemo$BsFile.make(/* array */[])), "root");

/*  Not a pure module */
